### ISSUE TITLE
容器当中占位元素的类名不对

### ISSUE THREAD

**Issue by zboMa** [KNXCloud/lowcode-engine-vue#16]
# 复现工具
本项目的demo，和lowcode-engine.cn提供的demo。分别添加一个容器物料，查看容器物料中占位元素的情况。

本项目demo中的情形

![5ae0612b2efcd3a817e5ef1929b2753](https://user-images.githubusercontent.com/26337768/177095396-29ac4197-e238-4831-9aef-ede6951a13c6.png)

官方demo中的情形

![27128c4f1663d82f730116330ff239d](https://user-images.githubusercontent.com/26337768/177095468-aad674fe-3c72-4362-a81e-62ed958f984c.png)

# 问题
可以看到一个是渲染的lc-container，一个是渲染的lc-container-placeholder，在渲染lc-container的情况下，当容器宽度小于lc-container文字宽度的时候，文字不换行，会撑开容器导致宽度不对，而lc-container-placeholder则会在这时文字换行，不会有宽度问题。
如下：
lc-container
![image](https://user-images.githubusercontent.com/26337768/177095741-61a2a587-7264-44e5-a97a-9c0b88791a18.png)
lc-container-placeholder
![image](https://user-images.githubusercontent.com/26337768/177095796-c9e5d66f-d718-44f8-ac3d-b4cb67792e3d.png)

# 代码
对比：
本项目中vue-renderer/src/core/use.ts:82
```ts
if (isDesignMode && node?.isContainer()) return h('div', { class: 'lc-container' });
```
官方项目react-renderer/src/renderer-view.tsx:239
```ts
// 如果是容器 && 无children && 高宽为空 增加一个占位容器，方便拖动
if (
            !viewProps.dataSource &&
            leaf?.isContainer() &&
            (children == null || (Array.isArray(children) && !children.length)) &&
            (!viewProps.style || Object.keys(viewProps.style).length === 0)
          ) {
            children = (
              <div className="lc-container-placeholder" style={viewProps.placeholderStyle}>
                {viewProps.placeholder || '拖拽组件或模板到这里'}
              </div>
            );
          }
```
对于容器中占位元素的处理不同。

而引擎中关于lc-container-placeholder的处理只有此一处，lc-container的处理也只有slot一处，所以我认为lc-container是给slot用的，而lc-container-placeholder是给容器占位元素用的。

从官方的注释当中也可以看出端倪。

**Comment by keuby** [comment]
可以给一个复现的 demo 仓库么，因为我需要确保修复了这个问题

**Comment by zboMa** [comment]
我fork了demo，并做了一些修改，clone下来安装运行即可看到效果。
https://github.com/zboMa/lowcode-engine-demo
![image](https://user-images.githubusercontent.com/26337768/177104782-41f0bb98-e228-4538-94cf-da358fdb6b0a.png)

**Comment by zboMa** [comment]
lc-container中的文字是用before伪类添加的，而lc-container-placeholder则是div下的text node添加的文本。
lowcode-engine-vue中vue-simulator-renderer/src/simulator.less:38可以看到，两个类名的样式也是有区别的。
```less

.lc-container {
  &:empty {
    display: flex;
    align-items: center;
    min-width: 140px;
    height: 66px;
    max-height: 100%;
    overflow: hidden;
    color: #a7b1bd;
    text-align: center;
    background: #f2f3f5;
    outline: 1px dashed rgb(31 56 88 / 20%);
    outline-offset: -1px !important;

    &::before {
      z-index: 1;
      width: 100%;
      font-size: 14px;
      white-space: nowrap;
      content: '\62D6\62FD\7EC4\4EF6\6216\6A21\677F\5230\8FD9\91CC';
    }
  }
}

.lc-container-placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  min-height: 60px;
  color: rgb(167 177 189);
  font-size: 14px;
  background-color: rgb(240 240 240);
  border: 1px dotted;

  &.lc-container-locked {
    background: #eccfcf;
  }
}
```
